# data.py
products = [
    {
        "id": 1,
        "category": "snowboards",
        "name": "Burton Custom",
        "brand": "Burton",
        "level": "intermediate",
        "style": "all-mountain",
        "price": 520,
        "is_sale": True,
        "is_new": False,
        "image": "icons/id1.png",
        "desc": "Універсальна дошка для парку і гір."
    },
    {
        "id": 2,
        "category": "snowboards",
        "name": "GNU Riders Choice",
        "brand": "GNU",
        "level": "advanced",
        "style": "freestyle",
        "price": 610,
        "is_sale": False,
        "is_new": True,
        "image": "icons/id2.png",
        "desc": "Фрістайл, пружність, стабільність на швидкості."
    },
    {
        "id": 3,
        "category": "skis",
        "name": "Atomic Bent 90",
        "brand": "Atomic",
        "level": "intermediate",
        "style": "all-mountain",
        "price": 480,
        "is_sale": False,
        "is_new": True,
        "image": "icons/id3.png",
        "desc": "Легкі лижі для універсального катання."
    },
    {
        "id": 4,
        "category": "snowboards",
        "name": "Process",
        "brand": "Burton",
        "level": "Intermediate",
        "style": "Freestyle",
        "price": 530,
        "is_sale": False,
        "is_new": True,
        "image": "icons/id4.png",
        "desc": "Легкий сноуборд для універсального катання."
    },
    {
        "id": 5,
        "category": "snowboards",
        "name": "Defenders of Awesome",
        "brand": "Capita",
        "level": "Advanced",
        "style": "Freestyle",
        "price": 640,
        "is_sale": False,
        "is_new": False,
        "image": "icons/id5.png",
        "desc": "Легкий сноуборд для універсального катання.",
    },
    {
        "id": 6,
        "category": "snowboards",
        "name": "Mountain Twin",
        "brand": "Jones",
        "level": "Expert",
        "style": "Freeride",
        "price": 525,
        "is_sale": False,
        "is_new": False,
        "image": "icons/id6.png",
        "desc": "Легкий сноуборд для універсального катання.",
    },
    {
        "id": 7,
        "category": "snowboards",
        "name": "Warpig",
        "brand": "Ride",
        "price": 670,
        "style": "All-Mountain",
        "level": "Intermediate",
        "is_sale": False,
        "is_new": False,
        "image": "icons/id7.png",
        "desc": "Легкий сноуборд для універсального катання.",
    },
    {
        "id": 8,
        "category": "snowboards",
        "brand": "Salomon",
        "name": "Assassin",
        "price": 550,
        "style": "All-Mountain",
        "level": "Advanced",
        "is_sale": False,
        "is_new": False,
        "image": "icons/id8.png",
        "desc": "Легкий сноуборд для універсального катання.",
    },
    {
        "id": 9,
        "category": "skis",
        "name": "E stance",
        "brand": "Salomon",
        "level": "expert",
        "style": "freestyle",
        "price": 520,
        "is_sale": False,
        "is_new": False,
        "image": "icons/id9.png",
        "desc": "Легкі лижі для універсального катання."
    },
    {
        "id": 10,
        "category": "skis",
        "name": "Arctic Glide 102",
        "brand": "Nordica",
        "level": "expert",
        "style": "all-mountain",
        "price": 749,
        "is_sale": False,
        "is_new": True,
        "image": "icons/id10.png",
        "desc": "Легкі лижі для універсального катання."
    },
    {
        "id": 11,
        "category": "skis",
        "name": "Summit Raptor X",
        "brand": "Salomon",
        "level": "intermediate",
        "style": "free-ride",
        "price": 899,
        "is_sale": False,
        "is_new": False,
        "image": "icons/id11.png",
        "desc": "Легкі лижі для універсального катання."
    },
    {
        "id": 12,
        "category": "skis",
        "name": "Frostline Elite 88",
        "brand": "Atomic",
        "level": "intermediate",
        "style": "all-mountain",
        "price": 679,
        "is_sale": True,
        "is_new": False,
        "image": "icons/id12.png",
        "desc": "Легкі лижі для універсального катання."
    },
]
